name: Sample GitHub Workflow
run-name: Deploy to Preprod
on:
  pull_request:
    branches: [main]
      
jobs:
  Deploy-to-Preprod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: curl -X POST -d api_key=${{ secrets.API_KEY }} -d environment=preprod -d sha=${{ github.sha }} https://app.sleuth.io/api/1/deployments/lem00r/sleuth-actions/register_deploy
